### ISSUE TITLE
Before publish

### ISSUE THREAD

**Issue by H4ad** [kibertoad/better-fd-slicer#2]
We should at least wait a week before publishing because of https://github.com/andrewrk/node-fd-slicer/issues/7, just to see if we can merge our changes in their repo instead of forking the code entirely.

If we don't get any response, then we can publish.

But we can continue the rewriting, docs, etc... without waiting for the response.

**Comment by kibertoad** [comment]
Agreed!

**Comment by H4ad** [comment]
Closing since we didn't get any new from him and we publish our first version.
